### ISSUE TITLE
Typo on experience

### ISSUE THREAD

**Issue by haaarshsingh** [pippinmole/pippinmole#1]
> 3️ 3 years experience with the C# environment

Might wanna make it "3" or "3.3" since C# hasn't been out for 33 years quite yet :P

**Comment by pippinmole** [comment]
Hi

This is fixed in [this](https://github.com/pippinmole/pippinmole/commit/a8139a417bcfa1b6014f8bbe1fe492ad89cae793) commit.

Thank you for your feedback.
